export declare const CONFIG_KEYS: {
    readonly PORT: "port";
    readonly NODE_ENV: "nodeEnv";
    readonly JWT_SECRET: "jwt.secret";
    readonly JWT_EXPIRATION_TIME: "jwt.expirationTime";
    readonly DATABASE_URL: "database.url";
    readonly DATABASE_REPLICA_URL: "database.replicaUrl";
    readonly AUTO_MIGRATE: "database.autoMigrate";
    readonly REDIS_URL: "redis.url";
    readonly MAIL_HOST: "mail.host";
    readonly MAIL_PORT: "mail.port";
    readonly MAIL_USER: "mail.user";
    readonly MAIL_PASS: "mail.pass";
    readonly FILE_UPLOAD_PROVIDER: "fileUpload.provider";
    readonly AWS_ACCESS_KEY: "AWS_ACCESS_KEY";
    readonly AWS_SECRET_ACCESS_KEY: "AWS_SECRET_ACCESS_KEY";
    readonly AWS_S3_REGION: "AWS_S3_REGION";
    readonly AWS_S3_BUCKET: "AWS_S3_BUCKET";
    readonly AWS_S3_UPLOAD_FOLDER: "AWS_S3_UPLOAD_FOLDER";
    readonly CLOUD_NAME: "CLOUD_NAME";
    readonly CLOUDINARY_API_KEY: "CLOUDINARY_API_KEY";
    readonly CLOUDINARY_API_SECRET: "CLOUDINARY_API_SECRET";
    readonly CLOUDINARY_BASEURL: "CLOUDINARY_BASEURL";
    readonly CLOUD_UPLOAD_PRESET: "CLOUD_UPLOAD_PRESET";
};
